gpu: 0,1,2,3
height: 256
width: 256
pretrained_i3d_weight: /home/ksr/PECoP/model_rgb.pth
clip_len: 80
crop_sz: 224
lr: 0.01
bs: 32
num_workers: 4
epoch: 8
max_sample_rate: 5
max_segment: 4
fr: 3
max_save: 100
pf: 20
model: i3d
data_list: /home/amir/AQA/Datasets/PD/30_subjects_frames/frames/gait/label/train.list
rgb_prefix: /home/amir/AQA/Datasets/PD/30_subjects_frames/frames/
data_root: /home/zkl/Documents/Data/AQA/Sequence/MTL-AQA