gpu: 2,3
exp_name: MTL-I3D_USDL
height: 256
width: 256
ckpts: /home/ksr/PECoP/pretrained_weights/i3d_for_USDL.pt
clip_len: 80
crop_sz: 224


# optimizer
learn_rate: 0.01
weight_decay: 1e-4
momentum: 0.9
dampening: 0
nesterov: False
# scheduler
T_max: 22


bs_train: 32
bs_test: 64
num_workers: 4
epoch: 24
max_sample_rate: 5
max_segment: 4
fr: 1
max_save: 100
pf: 20
model: i3d
data_list: /home/amir/AQA/Datasets/PD/30_subjects_frames/frames/gait/label/train.list
rgb_prefix: /home/amir/AQA/Datasets/PD/30_subjects_frames/frames/
data_root: /home/zkl/Documents/Data/AQA/Sequence/MTL-AQA
